[package]
name = "math_3d_graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.25.0"
glfw = "0.31.0"
glow = "0.13.0"
image = "0.24.7"
imgui = "0.11.0"
imgui-glfw-rs = "0.4.1"
